### ISSUE TITLE
Warn if there are no `cc` command.

### ISSUE THREAD

**Issue by phadej** [haskell/ghcup#46] opened 2018-11-12 10:28 UTC
On a fresh Arch Linux install (try e.g. with `docker run -ti --rm base/archlinux`):

```
[root@4d020a477a06 ghcup]# ./ghcup install
Installing GHC-8.4.4 for Arch Linux on architecture x86_64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  145M  100  145M    0     0  13.3M      0  0:00:10  0:00:10 --:--:-- 17.7M
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
Build platform inferred as: x86_64-unknown-linux
Host platform inferred as: x86_64-unknown-linux
Target platform inferred as: x86_64-unknown-linux
GHC build  : x86_64-unknown-linux
GHC host   : x86_64-unknown-linux
GHC target : x86_64-unknown-linux
LLVM target: x86_64-unknown-linux
checking for path to top of build tree... /tmp/tmp.KF7V7gadPN/ghc-8.4.4
checking for perl... /usr/sbin/perl
checking for a BSD-compatible install... /usr/bin/install -c
checking for gfind... no
checking for find... /usr/sbin/find
checking whether ln -s works... yes
checking for gsed... sed
checking for gcc... no
checking for clang... no
configure: error: in `/tmp/tmp.KF7V7gadPN/ghc-8.4.4':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
Failed to install, consider updating this script via: ghcup upgrade
```

Upgrading is a valid thing to offer, but it won't help here. I think checking for existence of `make` and `cc` in `$PATH` will catch clear cases where there are no development tools installed.

---

Btw, sorry for spamming `ghcup` with issues; but I'd like it to become good enough I dare to recommend it! It's close, but not there yet.

**Comment by hasufell** [comment] 2018-11-12 10:33
As you can see configure doesn't just look for `cc`, but also for `clang`, so we would have to duplicate all the configure checking logic which is not reasonable imo. This seems to be a duplicate of: https://github.com/haskell/ghcup/issues/34

**Comment by hvr** [comment] 2018-11-12 11:03
@hasufell this is supposed to be a heuristic, not a faithful emulation of the `configure` logic, and the reasoning goes like this (at least the one I had in  https://github.com/haskell/ghcup/issues/8#issuecomment-434270296):

We merely want to catch the *common* case that *no* C compiler is installed, as this is a very common situation; and since we're assuming POSIX systems, if a c compiler is installed, it is very customary to have a `cc` executable in the `$PATH`; this doesn't need to be 100% accurate -- the lack of it, is a very good predictor that a subsequent attempt to install the GHC bindist *will* fail.

Also note, this is supposed to be merely a warning that the user should be able to ignore.

**Comment by phadej** [comment] 2018-11-12 11:05
I see. GHC's `configure.ac` has

```
AC_PROG_CC([gcc clang])
```

We can either replicate it, or just test for `cc` (I haven't seen a "normal" system with either one, but without `cc`).

I think `ghcup` should replicate that *part* of the logic. Perfectly, `ghcup` should realise that there are no development environment and tell directly what to do / install (e.g. `apt-get install build-essential libgmp10` on ubuntu, btw I'm not sure if that is enough).

Note that e.g. `rustup.sh` *just works* on a clean machine (I tried in docker with arch linux). As GHC installation is a bit more involved, it's probably very difficult (we don't want to ask for `sudo`); But we should try to help the user as much as possible. E.g. what packages to install on different distributions is a hidden knowledge; would be very good if `ghcup` accumulated that knowledge.

**Comment by hasufell** [comment] 2018-11-12 15:52
> Also note, this is supposed to be merely a warning that the user should be able to ignore/override.

Hmm, this is not really specific enough to act on. If it's just a warning, then the installation will just proceed anyway and then may or may not fail at configure stage.

Or do you want to require user interaction here to confirm before proceeding? That is probably possible, but really solves only a small subset.

> We can either replicate it

I don't particularly like that approach.

What GHC needs is checked at configure stage. Configure scripts are exactly what we have been using since decades to gradually figure out missing requirements. **Resuming configure stage for example is implementable and better than replicating already existing code.**

> Perfectly, `ghcup` should realise that there are no development environment and tell directly what to do / install (e.g. `apt-get install build-essential libgmp10` on ubuntu, btw I'm not sure if that is enough).

That is even harder to get right. These instructions are distro-specific, distro-version-specific and may be outdated, because they need to be synchronized with new packages/releases.

Such things can be documented in the README maybe, but outputting shell commands that may or may not be correct via ghcup is not very user friendly imo, let alone executing them *\*shiver\**.

> As GHC installation is a bit more involved, it's probably very difficult (we don't want to ask for `sudo`);

Asking for sudo are those kind of scripts I abort and instantly delete or tear apart and rewrite so they don't attempt to break my machine (although I don't even have sudo), because I just lost all faith ;)

> E.g. what packages to install on different distributions is a hidden knowledge; would be very good if `ghcup` accumulated that knowledge.

Actually, that is knowledge that belongs on the haskell download pages, no? And we could simply link to it (as we do during compilation, if compilation fails): **output error "You are likely missing dependencies, check \<url\> and resume installation via \<command\>"**

**Comment by phadej** [comment] 2018-11-12 16:11
> tell directly what to do / install

should be parsed as `tell directly what to (do | install)`. I.e. i don't think that executing anything system-wide is good idea. We agree on this.

> That is even harder to get right. These instructions are distro-specific, distro-version-specific and may be outdated, because they need to be synchronized with new packages/releases.

Tarballs are distro specific, and happen to work on other distributions. Supporting fedora, debian (and ubuntu) is not a much job, and letting people to contribute guidelines for other distributions is a good thing.

> Such things can be documented in the README

Given the nature of a problem `ghcup` tries to solve, outsourcing to README is bad user experience. Also having not-anymore-working commands in README is as bad as printing them out directly from the script. The maintenance cost is about the same.

> Actually, that is knowledge that belongs on the haskell download pages, no

I  suspect that info will live in the wiki, which few people care to update; and beginners won't have clear place to report if things don't work. `ghcup` has an opportunity to be good place to *codify* those install one-liners.

**Comment by hasufell** [comment] 2018-11-12 16:13
> `ghcup` has an opportunity to be good place to _codify_ those install one-liners.

Those one-liners are relevant outside of ghcup scope (as in: for anyone trying to use the bindists), so they should be documented in the right place, no?

**Comment by hasufell** [comment] 2019-04-11 02:30
we print system-reqs now for `bootstrap-haskell` and have a `ghcup print-system-reqs` subcommand. In addition, once https://github.com/haskell/ghcup/issues/11 is resolved, then it should be fine.

**Closed by hasufell** 2019-04-11 02:30 UTC
Labels: discussion
